### ISSUE TITLE
/dev/null on Windows can't be found

### ISSUE THREAD

**Issue by Litarvan** [jamiemansfield/ProPatcher#2]
Pretty simple error, on Windows 10 :

Caused by: java.io.FileNotFoundException: \dev\null (Le chemin dÆaccÞs spÚcifiÚ est introuvable)
        at com.cloudbees.diff.Diff.diff(Diff.java:25)
        at com.cloudbees.diff.Diff$diff.call(Unknown Source)
        at uk.jamierocks.propatcher.task.MakePatchesTask.process(MakePatchesTask.groovy:97)
        at uk.jamierocks.propatcher.task.MakePatchesTask$process.callCurrent(Unknown Source)
        at uk.jamierocks.propatcher.task.MakePatchesTask.doTask(MakePatchesTask.groovy:51)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        ... 75 more

**Comment by jamierocks** [comment]
Interesting - I'll give this a look when I get back later ;)

**Comment by Litarvan** [comment]
Created a Pull Request to fix this and other Windows bugs :) Think to the Windows compatilbity next time ! I always use Linux but during holidays i use my laptop under Windows so, i was blocked :(

If you could push this to the gradle repository so I can use it asap !

**Comment by jamierocks** [comment]
https://github.com/jamierocks/ProPatcher/commit/b02caa374320d3530f75a6291b00a3271988c7f5
